# Generated by Django 5.0.4 on 2024-05-19 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nombre")),
                (
                    "status",
                    models.BooleanField(
                        choices=[(1, "Activo"), (0, "Inactivo")],
                        default=True,
                        verbose_name="estado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Área",
                "verbose_name_plural": "areas",
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nombre")),
                (
                    "status",
                    models.BooleanField(
                        choices=[(1, "Activo"), (0, "Inactivo")],
                        default=True,
                        verbose_name="estado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cargo",
                "verbose_name_plural": "Cargos",
            },
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Nombre")),
                (
                    "last_name",
                    models.CharField(max_length=70, verbose_name="Apellidos"),
                ),
                ("birth_date", models.DateField(verbose_name="Fecha Nacimiento")),
                ("address", models.CharField(max_length=50, verbose_name="Dirección")),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Ejm : +51 963852741",
                        max_length=50,
                        verbose_name="Número de Télefono",
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(blank=True, null=True, verbose_name="Facebook Url"),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Instagram Url"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Correo electronico"
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        choices=[(1, "Activo"), (0, "Inactivo")],
                        default=True,
                        verbose_name="estado",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="employee.field",
                        verbose_name="Área",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="employee.position",
                        verbose_name="Cargo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trabajador",
                "verbose_name_plural": "Trabajadores",
            },
        ),
    ]
