# Generated by Django 5.0.4 on 2024-05-19 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Tema")),
                ("link", models.URLField(verbose_name="link")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("G", "Generales"),
                            ("A", "Área"),
                            ("D", "Directivos"),
                        ],
                        max_length=1,
                        verbose_name="Tipo de reunión",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="Fecha")),
                (
                    "field",
                    models.ForeignKey(
                        blank=True,
                        help_text="Seleccionar para reunión por área",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="employee.field",
                        verbose_name="Área",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="employee.worker",
                        verbose_name="Organizador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reunion",
                "verbose_name_plural": "Reuniones",
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, max_length=1, null=True, verbose_name="estado"
                    ),
                ),
                (
                    "justification",
                    models.CharField(max_length=150, verbose_name="justificacion"),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee.worker",
                        verbose_name="Trabajador",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="meetings.meeting",
                        verbose_name="Reunion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asistencia",
                "verbose_name_plural": "Asistencias",
            },
        ),
    ]
